server:
  port: 8082
  servlet:
    context-path: /self-reflection-api
spring:
  main:
    allow-bean-definition-overriding: true
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/qa-portal
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        ddl-auto: none
        jdbc:
          lob:
            non_contextual_creation=true:logging: true
  level:
    org.springframework.web: DEBUG
    com.swttech.bignash: DEBUG

qa:
  keycloak:
    config:
      file: keycloak.json


---
spring:
  profiles: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:database_user;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.H2Dialect

  h2:
     console:
        enabled: true
        path: /h2

  flyway:
    locations: classpath:/db/migration-test-base

logging:
  level:
    org.springframework.web: DEBUG
    com.qa.portal: DEBUG
