export const PORTAL_APPLICATIONS_API = 'core-api/applications';
export const REFLECTION_API = 'self-reflection-api/reflection';
export const REFLECTION_QUESTION_API = `self-reflection-api/reflection-question`;
export const QUESTION_API = `self-reflection-api/question`;
export const TRAINER_COHORTS_API = 'user-api/user/cohorts/1';
export const SELF_REFLECTION_QUESTION_API = 'self-reflection-api/question';
export const SELF_REFLECTIONS_API = 'self-reflection-api/reflections';
export const USER_API_COHORTS='user-api/user/cohorts';
export const USER_API_TRAINEES='user-api/cohort/getTrainees';