version: '3.7'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=qa-portal
  cv-ui:
    image: bobcrutchley/qa-cv-standalone:latest
    ports:
      - target: 4200
        published: 4200
  cv-api:
    image: bobcrutchley/cv-api:latest
    ports:
      - target: 8080
        published: 8080
    build: 
      context: ./qa-portal-services
      args:
        - PROJECT=cv-api
    environment:
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
