version: '3.7'
services:
  keycloak:
    image: jboss/keycloak:latest
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm.json
      - DB_DATABASE=qa-portal
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - PROXY_ADDRESS_FORWARDING=true
    volumes:
      - type: bind
        source: ./qa-portal-infra/keycloak/qa-portal-realm.json
        target: /tmp/realm.json
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=qa-portal
  nginx:
    image: nginx:alpine
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - keycloak
      - portal-core
      - core-api
      - user-api
      - self-reflection-api
      - course-api
      - cv-api
      - feedback-api
      - question-api
    ports:
      - target: 80
        published: 80
  portal-core:
    image: bobcrutchley/portal-core:latest
    build: ./qa-portal-angular
  core-api:
    image: bobcrutchley/core-api:latest
    build: 
      context: ./qa-portal-services
      args:
        - PROJECT=core-api
    environment:
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
  user-api:
    image: bobcrutchley/user-api:latest
    build: 
      context: ./qa-portal-services
      args:
        - PROJECT=user-api
    environment:
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
  self-reflection-api:
    image: bobcrutchley/self-reflection-api:latest
    build: 
      context: ./qa-portal-services
      args:
        - PROJECT=self-reflection
    environment:
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
  course-api:
    image: bobcrutchley/course-api:latest
    build: 
      context: ./qa-portal-services
      args:
        - PROJECT=course-api
    environment:
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
  cv-api:
    image: bobcrutchley/cv-api:latest
    build: 
      context: ./qa-portal-services
      args:
        - PROJECT=cv-api
    environment:
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
  feedback-api:
    image: bobcrutchley/feedback-api:latest
    build: 
      context: ./qa-portal-services
      args:
        - PROJECT=feedback-api
    environment:
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
  question-api:
    image: bobcrutchley/question-api:latest
    build: 
      context: ./qa-portal-services
      args:
        - PROJECT=question-api
    environment:
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
