apiVersion: v1
kind: Pod
metadata:
  name: postgres
  namespace: development
  labels: 
    app: postgres
spec:
  containers:
    - name: postgres
      image: delt0p/postgres:latest
      ports:
      - containerPort: 5432
      env:
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        - name: POSTGRES_USER
          value: keycloak
        - name: POSTGRES_PASSWORD
          value: keycloak           
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres
  volumes:
    - name: postgres
      persistentVolumeClaim:
       claimName: postgres
