version: '3.7'
services:
  portal-core:
    image: portal-core:latest
    build: ./qa-portal-angular
  core-api:
    image: jpeckover/core-api:latest
    build: 
      context: ./qa-portal-services
      args:
        - PROJECT=core-api
        - PORT=8081
    environment:
      - POSTGRES_HOST=postgres
  self-reflection:
    image: jpeckover/self-reflection:latest
    build: 
      context: ./qa-portal-services
      args:
        - PROJECT=self-reflection
        - PORT=8082
    environment:
      - POSTGRES_HOST=postgres
  user-api:
    image: jpeckover/user-api:latest
    build: 
      context: ./qa-portal-services
      args:
        - PROJECT=user-api
        - PORT=8084
    environment:
      - POSTGRES_HOST=postgres