apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
   server {
        listen 80;
        location / {
            return 200 "OK";
        }
        location /jenkins/ {
            proxy_pass http://jenkins:8080;
        }
        # keycloak
        location /auth {
            proxy_pass http://keycloak:8080;
        }
        # portal
        location / {
            proxy_pass http://portal-core;
        }
        # core-api
        location /core-api {
            proxy_pass http://core-api:8081;
        }
        # user-api 
        location /user-api {
            proxy_pass http://user-api:8084;
        }
        # self-reflection
        location /self-reflection {
            proxy_pass http://self-reflection:8082;
        }
    }
