apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
  namespace: development 
  labels: 
    app: user-api
spec:
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
      - name: user-api
        image: jpeckover/user-api:latest
        ports:
        - containerPort: 8084
