apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  namespace: development
  labels: 
    app: jenkins
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: jenkins
      securityContext:
        runAsUser: 1000
      image: jenkins/jenkins:latest
      ports:
      - containerPort: 8443
      env:
      - name: JENKINS_OPTS
        value: "--prefix=/jenkins"
      volumeMounts:
        - mountPath: "/var/jenkins_home"
          name: jenkins-home
  volumes:
    - name: jenkins-home
      persistentVolumeClaim:
        claimName: jenkins-home
