apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  labels: 
    app: jenkins
spec:
  securityContext:
    fsGroup: 1000
  serviceAccountName: jenkins-service-account
  containers:
    - name: jenkins
      securityContext:
        runAsUser: 1000
      image: bobcrutchley/jenkins:latest
      ports:
      - containerPort: 8080
      env:
      - name: JENKINS_OPTS
        value: "--prefix=/jenkins"
      volumeMounts:
        - mountPath: "/var/jenkins_home"
          name: jenkins-home
        - mountPath: "/var/run/docker.sock"
          name: docker-socket
  volumes:
    - name: jenkins-home
      persistentVolumeClaim:
        claimName: jenkins-home
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: File
