pipeline {
    agent any

    stages {
        stage('clone repo')
            steps{
                git branch: 'ci-kube', url: 'https://github.com/bob-crutchley/QA-Portal.git'
            }
        stage('docker-compose build') {
            steps {
                sh label: '', script: 'docker-compose build .'
            }
        }
        stage('Push to GCR') {
            steps {
                sh label: '', script: 'bash ./build/push-gcr.sh'
            }
        }
    }
}