pipeline {
    agent any

    stages {
        stage('clone repo') {
            steps{
                git branch: ${env.GITHUB_BRANCH}, url: ${env.GITHUB_REPO}
            }
        stage('docker-compose build') {
            steps {
                sh label: '', script: 'docker-compose build .'
            }
        }
        stage('Push to GCR') {
            steps {
                sh label: '', script: 'bash ./build/push-gcr.sh'
            }
        }
    }
}
}